name: ğŸ“ Lint Commit

on:
  workflow_call:

jobs:
  prettier:
    name: ğŸ“ Lint Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Project Setup
        uses: ./.github/actions/setup/

      - name: ğŸ” Run Prettier
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
        shell: bash
