name: ğŸ” Lint Prettier

on:
  workflow_call:

jobs:
  prettier:
    name: ğŸ” Lint Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Project Setup
        uses: ./.github/actions/setup/

      - name: ğŸ” Run Prettier
        run: npm run prettier:check
        shell: bash
